import = [
    # uncomment the flavour you want below:
    #   "~/.config/alacritty/catppuccin-latte.toml"
    # "~/.config/alacritty/catppuccin-frappe.toml"
    "~/.config/alacritty/catppuccin-macchiato.toml",
    # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"


[window]
opacity = 0.90
blur = false
padding.x = 8
padding.y = 8
decorations = "Buttonless"
decorations_theme_variant = "Dark" # "Dark"


[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
size = 14.0


# [keyboard]
# bindings = [{ key = "F11", action = "ToggleFullscreen" }]
